version: "3.8"
services:
  web:
    container_name: app_flask_api
    build: .
    ports:
      - "8080:8080"
    command: python3 wsgi.py
    depends_on:
      - redis
#    links:
#      - "redis://redis:63791"
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis_flask
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 3
